'use client';

/**
 * Synthesised cues, no audio files.
 *
 * A club projector laptop is exactly the machine that will fail to load three
 * MP3s from a flaky connection five minutes before the first race, so every
 * sound here is generated by the WebAudio oscillator at the moment it plays.
 * The context is created lazily on the first user gesture because browsers
 * refuse to start one any earlier.
 */

let ctx: AudioContext | null = null;
let enabled = true;

export function setSoundEnabled(on: boolean) {
  enabled = on;
}

export function primeAudio() {
  if (ctx || typeof window === 'undefined') return;
  const Ctor = window.AudioContext ?? (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
  if (!Ctor) return;
  try {
    ctx = new Ctor();
  } catch {
    ctx = null;
  }
}

function tone(freq: number, startIn: number, dur: number, type: OscillatorType, peak: number) {
  if (!enabled || !ctx) return;
  if (ctx.state === 'suspended') void ctx.resume();

  const t0 = ctx.currentTime + startIn;
  const osc = ctx.createOscillator();
  const gain = ctx.createGain();

  osc.type = type;
  osc.frequency.setValueAtTime(freq, t0);

  gain.gain.setValueAtTime(0.0001, t0);
  gain.gain.exponentialRampToValueAtTime(peak, t0 + 0.012);
  gain.gain.exponentialRampToValueAtTime(0.0001, t0 + dur);

  osc.connect(gain).connect(ctx.destination);
  osc.start(t0);
  osc.stop(t0 + dur + 0.05);
}

export const sfx = {
  beep: () => tone(660, 0, 0.16, 'square', 0.1),
  go: () => {
    tone(880, 0, 0.3, 'square', 0.16);
    tone(1320, 0.04, 0.34, 'triangle', 0.1);
  },
  coin: () => {
    tone(880, 0, 0.1, 'triangle', 0.12);
    tone(1320, 0.07, 0.16, 'triangle', 0.1);
  },
  chip: () => {
    tone(520, 0, 0.08, 'sine', 0.09);
    tone(780, 0.05, 0.12, 'sine', 0.07);
  },
  fanfare: () => {
    [523.25, 659.25, 783.99, 1046.5].forEach((f, i) =>
      tone(f, i * 0.13, 0.42, 'triangle', 0.17),
    );
  },
  milestone: () => {
    [659.25, 880].forEach((f, i) => tone(f, i * 0.1, 0.3, 'sine', 0.14));
  },
  photo: () => {
    tone(180, 0, 0.5, 'sawtooth', 0.09);
    tone(240, 0.12, 0.45, 'sawtooth', 0.07);
  },
  /* A surprise that helped: a rising whoop. */
  boost: () => {
    [523.25, 698.46, 1046.5].forEach((f, i) => tone(f, i * 0.055, 0.2, 'triangle', 0.13));
  },
  /* A surprise that hurt: the same shape, falling and duller. */
  stumble: () => {
    [392, 294, 208].forEach((f, i) => tone(f, i * 0.07, 0.24, 'sine', 0.11));
  },
  /* The lead changes hands. Two stabs, so it cuts through a noisy room. */
  leadChange: () => {
    tone(880, 0, 0.12, 'square', 0.13);
    tone(1174.66, 0.1, 0.22, 'square', 0.12);
  },
  /* Halfway. One clang of the lap bell. */
  bell: () => {
    tone(1568, 0, 0.55, 'sine', 0.12);
    tone(2093, 0.02, 0.4, 'sine', 0.06);
  },
};
